// GENERATED by scripts/generate-brand-assets.mjs — do not edit by hand.
// Tiny branded LQIP for next/image `placeholder="blur"`.

export const blurDataURL =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAUCAYAAADskT9PAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAPUlEQVR42mMQERH6P5CYYdQBow4gVmFWgx4Ghslpaalh4FEHjDqArrmALg7AZ8moA0YdMOC5YLQ2HNIOAABbtDhcaj9HkgAAAABJRU5ErkJggg==";

/** Full-size branded placeholders, for posters and empty media slots. */
export const placeholders = {
  "16x9": "/placeholder/placeholder-16x9.png",
  "4x3": "/placeholder/placeholder-4x3.png",
  "3x2": "/placeholder/placeholder-3x2.png",
  "1x1": "/placeholder/placeholder-1x1.png",
} as const;
