import type { Metadata, Viewport } from "next";
import { Barlow_Condensed, IBM_Plex_Sans, IBM_Plex_Mono } from "next/font/google";
import "./globals.css";
import SmoothScroll from "@/components/providers/SmoothScroll";
import Preloader from "@/components/layout/Preloader";
import { site } from "@/lib/content";

const barlow = Barlow_Condensed({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-barlow",
  display: "swap",
});

const plexSans = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-plex-sans",
  display: "swap",
});

const plexMono = IBM_Plex_Mono({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
  variable: "--font-plex-mono",
  display: "swap",
});

const SITE_URL = "https://kodoai.dev";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: "kodoAI — If it's manual and measurable, it can be automated",
  description: site.sub,
  applicationName: site.name,
  openGraph: {
    title: "kodoAI — Automation Agency",
    description: site.sub,
    url: SITE_URL,
    siteName: site.name,
    images: ["/reference/banner.png"],
    type: "website",
  },
  // Every file below is generated by scripts/generate-brand-assets.mjs.
  icons: {
    icon: [
      { url: "/icons/favicon.svg", type: "image/svg+xml" },
      { url: "/icons/favicon-16x16.png", sizes: "16x16", type: "image/png" },
      { url: "/icons/favicon-32x32.png", sizes: "32x32", type: "image/png" },
      { url: "/icons/favicon-48x48.png", sizes: "48x48", type: "image/png" },
      { url: "/icons/android-chrome-192x192.png", sizes: "192x192", type: "image/png" },
      { url: "/icons/android-chrome-512x512.png", sizes: "512x512", type: "image/png" },
    ],
    shortcut: ["/favicon.ico"],
    apple: [
      { url: "/icons/apple-touch-icon.png", sizes: "180x180" },
      { url: "/icons/apple-touch-icon-167x167.png", sizes: "167x167" },
      { url: "/icons/apple-touch-icon-152x152.png", sizes: "152x152" },
    ],
    // Safari pinned tabs recolour a monochrome mask with the given colour.
    other: [{ rel: "mask-icon", url: "/icons/safari-pinned-tab.svg", color: "#c8f060" }],
  },
  manifest: "/site.webmanifest",
  other: { "msapplication-config": "/browserconfig.xml" },
};

// Mirrors --bg / --accent in globals.css: meta tags cannot read CSS variables,
// so these two are the only places a token value is repeated as a literal.
export const viewport: Viewport = {
  themeColor: "#0c0c0b",
  colorScheme: "dark",
};

/** schema.org Organization — gives search engines the canonical name + logo. */
const organizationJsonLd = {
  "@context": "https://schema.org",
  "@type": "Organization",
  name: site.name,
  url: SITE_URL,
  logo: `${SITE_URL}/brand/kodoai-logo-seo.png`,
  image: `${SITE_URL}/brand/kodoai-email-banner.png`,
  description: site.sub,
  email: site.email,
  slogan: site.tagline,
  sameAs: ["https://www.linkedin.com/in/soban-ahmad-malik/"],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${barlow.variable} ${plexSans.variable} ${plexMono.variable}`}>
      <body>
        {/* Global shell for every route. Per-route chrome (Header/Footer) lives
            in the (site) group layout; case study pages bring their own nav. */}
        <SmoothScroll>{children}</SmoothScroll>
        <div className="grain" aria-hidden />
        <Preloader />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationJsonLd) }}
        />
      </body>
    </html>
  );
}
